name: dbus_annotations
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  dbus: 0.7.11

dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0
